variables:
  IMAGE_OPENJDK_MAVEN: maven:3-jdk-8

stages:
  - clean
  - build
  - test

clean:
  image: $IMAGE_OPENJDK_MAVEN
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - sh $CI_PROJECT_DIR/mvn clean

build:
  image: $IMAGE_OPENJDK_MAVEN
  stage: build
  script:
    - echo "Compiling the code..."
    - sh $CI_PROJECT_DIR/mvn package
  artifacts:
    paths:
      - target/demo-spring-0.0.1-SNAPSHOT.jar

unit-test:
  image: $IMAGE_OPENJDK_GRADLE
  stage: test
  script:
    - echo "Running unit tests..."
    - sh $CI_PROJECT_DIR/mvn test -Dtest="com.example.spring.demospring.*"